import type { MathQuill } from "mathquill/mathquill.ts";

export const config: MathQuill.v3.Config = {
  restrictMismatchedBrackets: true,
  supSubsRequireOperand: true,
  autoCommands: ["pi", "sqrt", "Gamma"].join(" "),
  autoOperatorNames: [
    "sin",
    "cos",
    "tan",
    "csc",
    "sec",
    "cot",
    "sinh",
    "cosh",
    "tanh",
    "csch",
    "sech",
    "coth",
    "arcsin",
    "arccos",
    "arctan",
    "arccsc",
    "arcsec",
    "arccot",
    "arcsinh",
    "arccosh",
    "arctanh",
    "arccsch",
    "arcsech",
    "arccoth",
    "ln",
    "log",
    "abs",
    "arg",
    "sign",
    "sgn",
    "exp",
    "cis",
    "floor",
    "round",
    "ceil",
    "conj",
    "Re",
    "Im",
  ].join(" "),
};
